import React, { useMemo } from 'react';
import { MapContainer, TileLayer, Marker, Popup } from 'react-leaflet';
import L from 'leaflet';
import { Bus, UrbanEvent, MapLayerFilterState } from '../../types';
import { useUrbanEye } from '../../context/UrbanEyeContext';

interface LightCityMapProps {
  buses?: Bus[];
  events?: UrbanEvent[];
  filters?: MapLayerFilterState;
  height?: string;
  center?: [number, number];
  zoom?: number;
}

// Check if an event was generated by live edge AI inference
export const isLiveEvent = (evt: UrbanEvent): boolean => {
  return Boolean(
    evt.isLiveDetection ||
    evt.sourceFilename ||
    evt.evidenceDataUri ||
    (evt.evidenceUrl && evt.evidenceUrl.includes('/api/evidence/'))
  );
};

// Function to generate custom SVG pins for various event types with live pulse badge
const createCustomPin = (
  color: string,
  _label: string,
  iconType: string,
  isLive: boolean = false
) => {
  const livePulseHtml = isLive
    ? `
      <span style="
        position: absolute;
        top: -4px;
        right: -4px;
        display: flex;
        height: 12px;
        width: 12px;
        z-index: 10;
      ">
        <span style="
          animation: ping 1.5s cubic-bezier(0, 0, 0.2, 1) infinite;
          position: absolute;
          display: inline-flex;
          height: 100%;
          width: 100%;
          border-radius: 9999px;
          background-color: #10B981;
          opacity: 0.85;
        "></span>
        <span style="
          position: relative;
          display: inline-flex;
          border-radius: 9999px;
          height: 12px;
          width: 12px;
          background-color: #059669;
          border: 1.5px solid white;
        "></span>
      </span>
      <span style="
        position: absolute;
        inset: -4px;
        border-radius: 50%;
        border: 2px solid #10B981;
        opacity: 0.7;
        animation: pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite;
      "></span>
    `
    : '';

  return L.divIcon({
    className: 'custom-map-marker',
    html: `
      <div style="position: relative; display: flex; align-items: center; justify-content: center;">
        ${livePulseHtml}
        <div style="
          width: ${isLive ? '30px' : '28px'};
          height: ${isLive ? '30px' : '28px'};
          border-radius: 50%;
          background: ${color};
          border: ${isLive ? '2.5px solid #10B981' : '2px solid white'};
          box-shadow: ${
            isLive
              ? '0 0 14px rgba(16, 185, 129, 0.6), 0 4px 12px rgba(34, 57, 60, 0.35)'
              : '0 4px 12px rgba(34, 57, 60, 0.35)'
          };
          display: flex;
          align-items: center;
          justify-content: center;
          color: white;
          font-weight: bold;
          font-size: ${isLive ? '12px' : '11px'};
        ">
          ${iconType}
        </div>
        <div style="
          position: absolute;
          bottom: -4px;
          width: 0;
          height: 0;
          border-left: 5px solid transparent;
          border-right: 5px solid transparent;
          border-top: 6px solid ${color};
        "></div>
      </div>
    `,
    iconSize: [30, 36],
    iconAnchor: [15, 36],
    popupAnchor: [0, -34],
  });
};

const busIcon = L.divIcon({
  className: 'bus-map-marker',
  html: `
    <div style="position: relative; display: flex; align-items: center; justify-content: center;">
      <div style="
        width: 32px;
        height: 32px;
        border-radius: 8px;
        background: #22393C;
        border: 2px solid #AFBB98;
        box-shadow: 0 4px 14px rgba(34, 57, 60, 0.4);
        display: flex;
        align-items: center;
        justify-content: center;
        color: #AFBB98;
        font-weight: 800;
        font-size: 12px;
      ">
        🚌
      </div>
      <div style="
        position: absolute;
        bottom: -4px;
        width: 0;
        height: 0;
        border-left: 5px solid transparent;
        border-right: 5px solid transparent;
        border-top: 5px solid #22393C;
      "></div>
    </div>
  `,
  iconSize: [32, 36],
  iconAnchor: [16, 36],
  popupAnchor: [0, -34],
});

export const LightCityMap: React.FC<LightCityMapProps> = ({
  buses = [],
  events = [],
  filters,
  height = '480px',
  center = [18.5204, 73.8567],
  zoom = 13,
}) => {
  const { navigateToEventLogWithEvent } = useUrbanEye();

  // Filter events based on active checkboxes with robust compound category matching
  const filteredEvents = useMemo(() => {
    if (!filters) return events;
    return events.filter((evt) => {
      const cat = (evt.category || '').toLowerCase();
      const type = (evt.type || '').toLowerCase();

      // 1. Road Damage / Potholes
      if (
        cat.includes('pothole') ||
        cat.includes('road damage') ||
        type === 'road_damage' ||
        type === 'pothole'
      ) {
        return filters.roadDamage;
      }

      // 2. Traffic & Congestion
      if (
        cat.includes('traffic') ||
        cat.includes('congestion') ||
        type === 'traffic_congestion' ||
        type === 'traffic'
      ) {
        return filters.traffic;
      }

      // 3. Vehicles
      if (
        cat.includes('vehicle') ||
        type === 'vehicle_detection' ||
        type === 'vehicle'
      ) {
        return filters.vehicles;
      }

      // 4. Safety / Pedestrian Risk
      if (
        cat.includes('safety') ||
        cat.includes('pedestrian') ||
        type === 'pedestrian_risk' ||
        type === 'safety'
      ) {
        return filters.safety;
      }

      // 5. Accidents / Incidents
      if (
        cat.includes('accident') ||
        cat.includes('incident') ||
        type === 'accident'
      ) {
        return filters.accidents;
      }

      // 6. Waterlogging
      if (
        cat.includes('waterlog') ||
        type === 'waterlogging'
      ) {
        return filters.waterlogging;
      }

      // 7. Infrastructure Deficiencies
      if (
        cat.includes('infrastructure') ||
        cat.includes('sign') ||
        type === 'infrastructure_deficiency'
      ) {
        return filters.infrastructure;
      }

      // 8. ANPR / OCR Events
      if (
        cat.includes('anpr') ||
        cat.includes('ocr') ||
        type === 'anpr_ocr'
      ) {
        return filters.anprOcr;
      }

      return true;
    });
  }, [events, filters]);

  // Determine marker icon per event
  const getEventIcon = (evt: UrbanEvent) => {
    const isLive = isLiveEvent(evt);
    const cat = (evt.category || '').toLowerCase();
    const type = (evt.type || '').toLowerCase();

    if (cat.includes('pothole') || type === 'pothole') {
      return createCustomPin('#46707E', 'P', '⚠️', isLive);
    }
    if (cat.includes('road damage') || type === 'road_damage') {
      return createCustomPin('#6B8B81', 'RD', '🛠️', isLive);
    }
    if (cat.includes('traffic') || cat.includes('congestion') || type === 'traffic_congestion') {
      return createCustomPin('#546F67', 'T', '🚦', isLive);
    }
    if (cat.includes('vehicle') || type === 'vehicle_detection') {
      return createCustomPin('#22393C', 'V', '🚗', isLive);
    }
    if (cat.includes('safety') || cat.includes('pedestrian') || type === 'pedestrian_risk') {
      return createCustomPin('#93A17B', 'S', '🚸', isLive);
    }
    if (cat.includes('accident') || cat.includes('incident') || type === 'accident') {
      return createCustomPin('#B91C1C', 'A', '💥', isLive);
    }
    if (cat.includes('waterlog') || type === 'waterlogging') {
      return createCustomPin('#355560', 'W', '🌊', isLive);
    }
    if (cat.includes('infrastructure') || cat.includes('sign') || type === 'infrastructure_deficiency') {
      return createCustomPin('#AFBB98', 'I', '🏗️', isLive);
    }
    if (cat.includes('anpr') || cat.includes('ocr') || type === 'anpr_ocr') {
      return createCustomPin('#46707E', 'O', '📷', isLive);
    }
    return createCustomPin('#46707E', 'E', '📍', isLive);
  };

  return (
    <div className="w-full rounded-2xl overflow-hidden shadow-glass border border-[#46707E]/20 relative z-10">
      <MapContainer
        center={center}
        zoom={zoom}
        style={{ height, width: '100%' }}
        scrollWheelZoom={false}
      >
        {/* CARTO Positron Light Basemap with authenticated key */}
        <TileLayer
          attribution='&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions" target="_blank" rel="noreferrer">CARTO</a>'
          url={`https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png${
            import.meta.env.VITE_CARTO_API_KEY
              ? `?key=${import.meta.env.VITE_CARTO_API_KEY}`
              : ''
          }`}
          subdomains="abcd"
          maxZoom={19}
        />

        {/* Bus Markers (when toggled on) */}
        {(!filters || filters.buses) &&
          buses.map((bus) => (
            <Marker key={bus.id} position={bus.coordinates} icon={busIcon}>
              <Popup>
                <div className="p-3.5 min-w-[220px]">
                  <div className="flex items-center justify-between border-b border-[#46707E]/20 pb-2 mb-2">
                    <span className="font-bold text-sm text-[#22393C] flex items-center gap-1.5">
                      <span className="w-2 h-2 rounded-full bg-emerald-500"></span>
                      {bus.id}
                    </span>
                    <span className="text-[11px] font-semibold px-2 py-0.5 rounded bg-[#46707E]/15 text-[#46707E]">
                      {bus.route}
                    </span>
                  </div>
                  <div className="space-y-1.5 text-xs text-[#22393C]/80">
                    <div className="flex justify-between">
                      <span className="text-gray-500">Driver:</span>
                      <span className="font-medium text-[#22393C]">{bus.driverId}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-gray-500">Speed:</span>
                      <span className="font-mono font-semibold text-[#46707E]">{bus.speed}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-gray-500">Location:</span>
                      <span className="font-medium text-[#22393C]">{bus.location}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-gray-500">Open Issues:</span>
                      <span className="font-bold text-amber-700">{bus.openIssues}</span>
                    </div>
                  </div>
                </div>
              </Popup>
            </Marker>
          ))}

        {/* Urban Event Markers */}
        {filteredEvents.map((evt) => {
          const isLive = isLiveEvent(evt);
          const evidenceSrc =
            evt.evidenceDataUri ||
            evt.evidenceUrl ||
            (evt.evidenceFrame &&
            (evt.evidenceFrame.startsWith('/') ||
              evt.evidenceFrame.startsWith('data:') ||
              evt.evidenceFrame.startsWith('http'))
              ? evt.evidenceFrame
              : null);

          return (
            <Marker key={evt.id} position={evt.coordinates} icon={getEventIcon(evt)}>
              <Popup>
                <div className="p-3 min-w-[260px] max-w-[290px]">
                  {/* Header */}
                  <div className="flex items-start justify-between border-b border-[#46707E]/20 pb-2 mb-2">
                    <div>
                      <h4 className="font-bold text-sm text-[#22393C] leading-tight">{evt.className}</h4>
                      <span className="text-[10px] uppercase font-mono text-[#46707E] font-semibold">
                        {evt.id} • {evt.category}
                      </span>
                    </div>
                    <span
                      className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${
                        evt.severity === 'HIGH' || evt.severity === 'CRITICAL'
                          ? 'bg-rose-100 text-rose-700 border border-rose-200'
                          : evt.severity === 'MEDIUM'
                          ? 'bg-amber-100 text-amber-800 border border-amber-200'
                          : 'bg-emerald-100 text-emerald-800 border border-emerald-200'
                      }`}
                    >
                      {evt.severity}
                    </span>
                  </div>

                  {/* Mode / Telemetry Badge */}
                  <div className="mb-2 flex items-center justify-between">
                    {isLive ? (
                      <span className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded text-[10px] font-bold bg-emerald-50 text-emerald-800 border border-emerald-300">
                        <span className="relative flex h-2 w-2">
                          <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
                          <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-600"></span>
                        </span>
                        LIVE EDGE AI DETECTION
                      </span>
                    ) : (
                      <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-semibold bg-gray-100 text-gray-700 border border-gray-200">
                        <span>📋</span>
                        PROTOTYPE BASELINE CONTEXT
                      </span>
                    )}
                    {evt.confidence !== undefined && (
                      <span className="text-[10px] font-mono font-bold text-[#46707E] bg-[#46707E]/10 px-1.5 py-0.5 rounded">
                        {evt.confidence}% CONF
                      </span>
                    )}
                  </div>

                  {/* Corroboration Status Strip */}
                  <div className="mb-2 p-1.5 rounded-lg bg-[#22393C]/5 border border-[#46707E]/15 flex items-center justify-between text-[11px]">
                    <span className="text-gray-500 font-semibold">Corroboration:</span>
                    <span
                      className={`font-bold px-1.5 py-0.5 rounded text-[10px] ${
                        evt.corroborationStatus === 'VERIFIED'
                          ? 'bg-emerald-100 text-emerald-800'
                          : evt.corroborationStatus === 'CORROBORATED'
                          ? 'bg-teal-100 text-teal-800'
                          : evt.corroborationStatus === 'POTENTIAL_FALSE_POSITIVE'
                          ? 'bg-rose-100 text-rose-800'
                          : evt.corroborationStatus === 'NEEDS_VERIFICATION'
                          ? 'bg-amber-100 text-amber-800'
                          : 'bg-blue-100 text-blue-800'
                      }`}
                    >
                      {evt.corroborationStatus === 'VERIFIED'
                        ? `🟢 Verified (${evt.participatingBuses?.length || 3} Buses)`
                        : evt.corroborationStatus === 'CORROBORATED'
                        ? `🟡 Corroborated (${evt.participatingBuses?.length || 2} Buses)`
                        : evt.corroborationStatus === 'POTENTIAL_FALSE_POSITIVE'
                        ? '🔴 False Positive Alert'
                        : evt.corroborationStatus === 'NEEDS_VERIFICATION'
                        ? '⚠️ Needs Verification'
                        : `🔵 Single Bus (${evt.busId})`}
                    </span>
                  </div>

                  {/* Evidence Thumbnail if available */}
                  {evidenceSrc && (
                    <div className="mb-2 rounded-lg overflow-hidden border border-[#46707E]/25 bg-black/5 max-h-[120px] flex items-center justify-center">
                      <img
                        src={evidenceSrc}
                        alt={`Evidence for ${evt.id}`}
                        className="w-full h-auto max-h-[120px] object-cover"
                        onError={(e) => {
                          if (evt.evidenceDataUri && e.currentTarget.src !== evt.evidenceDataUri) {
                            e.currentTarget.src = evt.evidenceDataUri;
                          } else {
                            e.currentTarget.style.display = 'none';
                          }
                        }}
                      />
                    </div>
                  )}

                  {/* Metadata fields */}
                  <div className="space-y-1 text-xs text-[#22393C]/80">
                    <div className="flex justify-between">
                      <span className="text-gray-500">Bus ID:</span>
                      <span className="font-semibold text-[#22393C]">{evt.busId}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-gray-500">Location:</span>
                      <span className="font-medium text-[#22393C] truncate max-w-[160px]" title={evt.locationName}>
                        {evt.locationName}
                      </span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-gray-500">GPS:</span>
                      <span className="font-mono text-[11px] text-gray-700">
                        {evt.coordinates[0].toFixed(4)}, {evt.coordinates[1].toFixed(4)}
                      </span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-gray-500">Time:</span>
                      <span className="font-medium text-[#22393C]">{evt.timeFormatted || evt.timestamp}</span>
                    </div>
                    {evt.contextNote && (
                      <div className="mt-1 pt-1 border-t border-[#46707E]/10 text-[11px] text-gray-600 line-clamp-2" title={evt.contextNote}>
                        {evt.contextNote}
                      </div>
                    )}
                  </div>

                  {/* Action Link to Event Log */}
                  <div className="mt-2.5 pt-2 border-t border-[#46707E]/15">
                    <button
                      type="button"
                      onClick={(e) => {
                        e.preventDefault();
                        e.stopPropagation();
                        navigateToEventLogWithEvent(evt.id);
                      }}
                      className="w-full text-center text-xs font-bold text-[#46707E] hover:text-[#22393C] transition-colors flex items-center justify-center gap-1.5 py-1.5 rounded bg-[#46707E]/10 hover:bg-[#46707E]/20 cursor-pointer"
                    >
                      <span>View in Event Log</span>
                      <span>→</span>
                    </button>
                  </div>
                </div>
              </Popup>
            </Marker>
          );
        })}
      </MapContainer>
    </div>
  );
};
